<?php

/**
 * CityEE site-wide configuration.
 * All multilingual texts, page data, and SEO content.
 */

return [

    // ─── Company Info ──────────────────────────────────────────
    'company' => [
        'name'        => 'CITY EE OÜ',
        'brand'       => 'CityEE',
        'phone'       => '+3725113411',
        'phone_display' => '(+372)5113411',
        'email'       => 'info@cityee.ee',
        'address'     => 'Viru väljak 2, Metro Plaza (3. korrus)',
        'city'        => 'Tallinn',
        'postal_code' => '10111',
        'region'      => 'Harjumaa',
        'country'     => 'EE',
        'whatsapp'    => 'https://wa.me/3725113411',
        'telegram'    => 'https://t.me/kinnisvaramaakler',
        'facebook'    => 'https://www.facebook.com/cityee.ee',
        'instagram'   => 'https://www.instagram.com/cityee_ee/',
        'linkedin'    => 'https://www.linkedin.com/in/kinnisvaramaakler/',
        'city24'      => 'https://www.city24.ee/company-detail/9898/city-ee-ou',
        'lat'         => 59.4361,
        'lng'         => 24.7537,
    ],

    'agent' => [
        'name'  => 'Aleksandr Primakov',
        'email' => 'aleksandr@cityee.ee',
        'phone' => '+372 511 3411',
        'photo' => '/assets/templates/offshors/img/ap1.png',
    ],

    // ─── Per-language navigation ───────────────────────────────
    'nav' => [
        'et' => [
            ['route' => 'home',         'label' => 'Pealeht',                  'title' => 'Pealeht'],
            ['route' => 'sell',         'label' => 'Kinnisvara vahendamine',   'title' => 'Kinnisvara müük parima võimaliku hinna ja parima võimaliku ajaga !'],
            ['route' => 'rent',         'label' => 'Kinnisvara üürileandmine', 'title' => 'Abi üürilepingu koostamisel'],
            ['route' => 'consultation', 'label' => 'Konsultatsioonid',         'title' => 'Konsulteerimine'],
            ['route' => 'contacts',     'label' => 'Kontaktid',                'title' => 'Kontaktid'],
        ],
        'ru' => [
            ['route' => 'home',         'label' => 'Главная',                          'title' => 'Главная'],
            ['route' => 'sell',         'label' => 'Продать недвижимость',              'title' => 'Надежный маклер в Таллинне'],
            ['route' => 'rent',         'label' => 'Сдать недвижимость в аренду',       'title' => 'Надежный маклер в Таллинне'],
            ['route' => 'consultation', 'label' => 'Kонсультации',                     'title' => 'Консультирование'],
            ['route' => 'contacts',     'label' => 'Контакты',                          'title' => 'Маклер Таллинн'],
        ],
        'en' => [
            ['route' => 'home',         'label' => 'Home',              'title' => 'Home'],
            ['route' => 'sell',         'label' => 'Sell Property',     'title' => 'Sell property in Tallinn with a reliable broker'],
            ['route' => 'rent',         'label' => 'Rent Out Property', 'title' => 'Rent out property in Tallinn'],
            ['route' => 'consultation', 'label' => 'Consultation',      'title' => 'Real estate consultation'],
            ['route' => 'contacts',     'label' => 'Contacts',          'title' => 'Contact us'],
        ],
    ],

    // ─── Sidebar menu ──────────────────────────────────────────
    'sidebar_title' => [
        'et' => 'Teenused',
        'ru' => 'Услуги',
        'en' => 'Services',
    ],

    // ─── Common UI strings ─────────────────────────────────────
    'ui' => [
        'et' => [
            'logo_text'       => 'KINNISVARATEHINGUTE PARTNER TALLINNAS',
            'order_call'      => 'Telli kõne',
            'send_inquiry'    => 'SAADA PÄRING',
            'send'            => 'Saada',
            'your_name'       => 'Teie nimi',
            'your_phone'      => 'Teie telefoni number',
            'your_email'      => 'Teie email',
            'your_comment'    => 'Teie komentaar',
            'call_whatsapp'   => "helista WhatsApp'i",
            'hours'           => '10.00 kuni 22.00',
            'contacts'        => 'Kontaktid',
            'objects'         => 'Objektid',
            'questions_call'  => 'Kas Teil on küsimusi? Helistage!',
            'how_sell'        => 'Kuidas edukalt kinnisvara müüa?',
            'write_now'       => 'KIRJUTAGE MEILE KOHE!',
            'advantages_title' => 'Meiega koostöö eelised',
            'adv_speed'       => 'OPERATIIVSELT',
            'adv_quality'     => 'KVALITEETSELT',
            'adv_confid'      => 'KONFIDENTSIAALSELT',
            'adv_reliable'    => 'USALDUSVÄÄRSELT',
            'about_title'     => 'CityEE — KINNISVARATEHINGUTE OPTIMEERIMISE PARTNER TALLINNAS JA HARJUMAAL',
            'about_p1'        => 'Meie abiga on võimalik müüa kinnisvara või anda üürile kiiresti ja soodsalt, kuna me kasutame kõige tõhusamat strateegiat ja turukanaleid.',
            'about_p2'        => 'Kinnisvara müügil on väga palju nüansse, alustades turupiirkonna analüüsiga, objekti dokumentatsiooni kontrollimise, õige turunduse ja kanalite valimisega reklaami jaoks, kuni parima krediidilahenduse ja juriidilise konsultatsiooni otsimiseni.',
            'about_p3'        => 'Parima teenuse garanteerimiseks soovitame sõlmida meiega ainuesinduslepingu.',
            'copyright'       => 'a. Kõik õigused kaitstud. Kinnisvara Büroo / Maakler Tallinnas ja Harjumaal / KINNISVARATEHINGUTE OPTIMEERIMISE PARTNER.',
            'read_more'       => 'Loe edasi',
        ],
        'ru' => [
            'logo_text'       => 'ПАРТНЁР ПО СДЕЛКАМ С НЕДВИЖИМОСТЬЮ В ТАЛЛИННЕ',
            'order_call'      => 'Заказать звонок',
            'send_inquiry'    => 'ОТПРАВИТЬ ЗАЯВКУ',
            'send'            => 'Отправить',
            'your_name'       => 'Ваше имя',
            'your_phone'      => 'Ваш номер телефона',
            'your_email'      => 'Ваш email',
            'your_comment'    => 'Ваш комментарий',
            'call_whatsapp'   => 'позвонить в WhatsApp',
            'hours'           => '10.00 до 22.00',
            'contacts'        => 'Контакты',
            'objects'         => 'Объекты',
            'questions_call'  => 'У вас есть вопросы? Звоните!',
            'how_sell'        => 'Как успешно продать недвижимость?',
            'write_now'       => 'НАПИШИТЕ НАМ СЕЙЧАС!',
            'advantages_title' => 'Преимущества работы с нами',
            'adv_speed'       => 'ОПЕРАТИВНО',
            'adv_quality'     => 'КАЧЕСТВЕННО',
            'adv_confid'      => 'КОНФИДЕНЦИАЛЬНО',
            'adv_reliable'    => 'НАДЕЖНО',
            'about_title'     => 'CityEE — ПАРТНЁР ПО ОПТИМИЗАЦИИ СДЕЛОК С НЕДВИЖИМОСТЬЮ В ТАЛЛИННЕ И ХАРЬЮМАА',
            'about_p1'        => 'С нашей помощью можно продать недвижимость или сдать в аренду быстро и выгодно, так как мы используем наиболее эффективную стратегию и маркетинговые каналы.',
            'about_p2'        => 'При продаже недвижимости существует множество нюансов, начиная с анализа рыночного сегмента, проверки документации объекта, выбора правильного маркетинга и каналов для рекламы, заканчивая поиском лучшего кредитного решения и юридической консультацией.',
            'about_p3'        => 'Для гарантии лучшего сервиса мы рекомендуем заключить с нами эксклюзивный договор.',
            'copyright'       => 'г. Все права защищены. Бюро по недвижимости / Маклер в Таллинне и Харьюмаа / ПАРТНЕР ПО ОПТИМИЗАЦИИ СДЕЛОК С НЕДВИЖИМОСТЬЮ.',
            'read_more'       => 'Читать далее',
        ],
        'en' => [
            'logo_text'       => 'YOUR REAL ESTATE PARTNER IN TALLINN',
            'order_call'      => 'Request a call',
            'send_inquiry'    => 'SEND INQUIRY',
            'send'            => 'Send',
            'your_name'       => 'Your name',
            'your_phone'      => 'Your phone number',
            'your_email'      => 'Your email',
            'your_comment'    => 'Your comment',
            'call_whatsapp'   => 'call via WhatsApp',
            'hours'           => '10:00 to 22:00',
            'contacts'        => 'Contacts',
            'objects'         => 'Listings',
            'questions_call'  => 'Have questions? Call us!',
            'how_sell'        => 'How to successfully sell property?',
            'write_now'       => 'WRITE TO US NOW!',
            'advantages_title' => 'Advantages of working with us',
            'adv_speed'       => 'PROMPTLY',
            'adv_quality'     => 'WITH QUALITY',
            'adv_confid'      => 'CONFIDENTIALLY',
            'adv_reliable'    => 'RELIABLY',
            'about_title'     => 'CityEE — REAL ESTATE DEAL OPTIMIZATION PARTNER IN TALLINN & HARJUMAA',
            'about_p1'        => 'With our help you can sell or rent out real estate quickly and profitably, because we use the most effective strategy and marketing channels.',
            'about_p2'        => 'There are many nuances in selling real estate, from market segment analysis and object documentation verification, to choosing the right marketing and advertising channels, to finding the best credit solution and legal consultation.',
            'about_p3'        => 'To guarantee the best service, we recommend signing an exclusive agreement with us.',
            'copyright'       => '. All rights reserved. Real Estate Bureau / Broker in Tallinn and Harjumaa / REAL ESTATE DEAL OPTIMIZATION PARTNER.',
            'read_more'       => 'Read more',
        ],
    ],

    // ─── SELL PAGE ─────────────────────────────────────────────
    'sell' => [
        'et' => [
            'meta_title'       => 'Kinnisvara müük Tallinnas | Audit ja strateegia | CityEE',
            'meta_description' => 'CityEE Kinnisvara pakub kvaliteetset vahendusteenust kinnisvara müümisel - Lühikese ajaga (1-1.5 kuud) ja parima hinnaga. Maakleriteenuste hind ( vahendustasu ) on minimaalne - 2% korteri maksumusest.',
            'h1'               => 'Kinnisvara vahendamine',
            'hero_subtitle'    => 'Kinnisvara müük parima võimaliku hinna ja parima võimaliku ajaga !',
            'hero_add'         => '',
            'hero_cta'         => 'Saada päring',
            'hero_bg'          => '/assets/templates/offshors/img/offshors.jpg',
            'intro'            => '<p><strong>KINNISVARAVAHENDUS</strong> Kinnisvara müük on sündmus, mis juhtub inimese elus harva, seetõttu parima ja kiirema tulemuse saavutamiseks tasub usaldada see protsess antud valdkonna spetsialistidele. Me aitame leida lahenduse nii era- kui äriklientidele.</p><p>Personaalse hinnapakkumise võib küsida meie konsultantidelt Tallinnas või saata meile päringu.</p>',
            'services_title'   => 'MEIE TEENUSE SISU:',
            'services' => [
                'Objekti kohta vajaliku informatsiooni kogumine, ettevalmistamine',
                'Õige müügihinna määramine',
                'Professionaalsed fotod',
                'Juriidiline konsultatsioon ja dokumentide õigsuse kontrollimine',
                'Aktiivne müük',
                'Anname teile regulaarselt müügitegevuse kohta tagasisidet',
                'Vajadusel korraldame kinnisvara presentatsiooni ja selle jaoks kõik vajalikud materjalid',
                'Kontrollime tehingu notariaalse tõestamise',
                'Teeme koostööd teiste maakleritega ja jagame vahendustasu kõigiga, kes toovad meile kliente',
            ],
            'pricing_title'   => 'TEENUSE PAKKUMISE HINNAD',
            'pricing_text'    => '<p><i>Tasu müügi korraldamise eest on kokkuleppeline. Sõltub kinnisvara müügihinnast, asukohast ja teenuse sisust, mida te ootate maaklerilt.</i></p><p><i>Keskmiselt on teenuste hind 2-5 % tehingusummast.</i></p>',
            'bonus'           => 'Sõlmides meiega ainusesinduslepingu, saate oma korteri müügiks maksimaalse reklaamipaketi minimaalse vahendustasuga <strong>AINULT 2% korteri müügihinnast !</strong>',
            'faq' => [
                ['q' => 'Kui kaua kinnisvara müük aega võtab?', 'a' => 'Keskmine müügiaeg on 1–1,5 kuud sõltuvalt objektist ja turuhinnast.'],
                ['q' => 'Mis on CityEE maaklertasu?', 'a' => 'Ainuesinduslepingu korral on vahendustasu ainult 2% müügihinnast. Standardtasu on 2–5% tehingusummast.'],
                ['q' => 'Kas tasuta kinnisvara hindamine on võimalik?', 'a' => 'Jah, ainuesinduslepingu sõlmimisel (vähemalt 3 kuuks) pakume tasuta kinnisvara hindamist.'],
            ],
            'answer_block' => [
                'question' => 'Kuidas müüa kinnisvara Tallinnas parima hinnaga?',
                'answer'   => 'CityEE teostab turuhinna auditi, töötab välja hinnastrateegia, leiab õiged reklaamikanalid ja juhib läbirääkimisi kuni notarini. Keskmine müügiaeg on 30–45 päeva, vahendustasu alates 2%.',
                'bullets'  => ['Turuhinna audit ja strateegia', 'Professionaalsed fotod ja reklaam', 'Läbirääkimised ostjatega', 'Juriidiline kontroll kuni notarini'],
            ],
            'voice_qa' => [
                ['q' => 'Kui palju maksab kinnisvara müük Tallinnas?', 'a' => 'CityEE maakleritasu on 2–5% tehingusummast. Ainuesinduslepinguga saab minimaaltasu 2%. Hindamine ja esimene konsultatsioon on tasuta.'],
                ['q' => 'Kui kiiresti müüb CityEE korteri?', 'a' => 'Keskmine müügiaeg on 30–45 päeva. Õige hinnastrateegia ja aktiivse reklaami korral on tulemus tihti kiirem — 2–3 nädalat.'],
            ],
        ],
        'ru' => [
            'meta_title'       => 'Продать недвижимость в Таллинне | Аудит цены и стратегия | CityEE',
            'meta_description' => 'CityEE предлагает качественные посреднические услуги при продаже недвижимости – за короткий срок (1-1.5 месяца) и по лучшей цене. Стоимость маклерских услуг (комиссия) минимальная — 2%.',
            'h1'               => 'Продажа недвижимости',
            'hero_subtitle'    => 'Продажа недвижимости по лучшей цене и в кратчайшие сроки!',
            'hero_add'         => '',
            'hero_cta'         => 'Отправить заявку',
            'hero_bg'          => '/assets/templates/offshors/img/offshors.jpg',
            'intro'            => '<p><strong>ПОСРЕДНИЧЕСКИЕ УСЛУГИ В СФЕРЕ НЕДВИЖИМОСТИ</strong> Продажа недвижимости — это событие, которое случается в жизни человека нечасто, поэтому для достижения наилучшего и быстрейшего результата стоит доверить этот процесс специалистам. Мы помогаем найти решение как частным, так и бизнес-клиентам.</p><p>За персональным ценовым предложением можно обратиться к нашим консультантам в Таллинне или отправить нам запрос.</p>',
            'services_title'   => 'СОДЕРЖАНИЕ НАШИХ УСЛУГ:',
            'services' => [
                'Сбор и подготовка необходимой информации об объекте',
                'Определение правильной цены продажи',
                'Профессиональные фотографии',
                'Юридическая консультация и проверка правильности документов',
                'Активная продажа',
                'Регулярно предоставляем вам обратную связь о ходе продаж',
                'При необходимости организуем презентацию недвижимости и все необходимые материалы',
                'Контролируем нотариальное оформление сделки',
                'Сотрудничаем с другими маклерами и делим комиссию со всеми, кто приводит нам клиентов',
            ],
            'pricing_title'   => 'СТОИМОСТЬ УСЛУГ',
            'pricing_text'    => '<p><i>Оплата за организацию продажи — по договоренности. Зависит от цены объекта, его расположения и содержания услуги, которую вы ожидаете от маклера.</i></p><p><i>В среднем стоимость услуг составляет 2-5% от суммы сделки.</i></p>',
            'bonus'           => 'Заключив с нами эксклюзивный договор, вы получаете максимальный рекламный пакет для продажи вашей квартиры с минимальной комиссией — <strong>ВСЕГО 2% от цены продажи квартиры!</strong>',
            'faq' => [
                ['q' => 'Сколько времени занимает продажа недвижимости?', 'a' => 'Среднее время продажи составляет 1–1,5 месяца в зависимости от объекта и рыночной цены.'],
                ['q' => 'Какова комиссия CityEE?', 'a' => 'При эксклюзивном договоре комиссия составляет всего 2% от цены продажи. Стандартная комиссия — 2–5% от суммы сделки.'],
                ['q' => 'Возможна ли бесплатная оценка недвижимости?', 'a' => 'Да, при заключении эксклюзивного договора (минимум на 3 месяца) мы предлагаем бесплатную оценку недвижимости.'],
            ],
            'answer_block' => [
                'question' => 'Как продать недвижимость в Таллинне по лучшей цене?',
                'answer'   => 'CityEE проводит аудит рыночной цены, разрабатывает стратегию ценообразования, находит правильные рекламные каналы и ведёт переговоры до нотариуса. Среднее время продажи — 30–45 дней, комиссия от 2%.',
                'bullets'  => ['Аудит рыночной цены и стратегия', 'Профессиональные фото и реклама', 'Переговоры с покупателями', 'Юридический контроль до нотариуса'],
            ],
            'voice_qa' => [
                ['q' => 'Сколько стоит продать квартиру в Таллинне?', 'a' => 'Комиссия маклера CityEE — 2–5% от суммы сделки. При эксклюзивном договоре — всего 2%. Оценка и первая консультация бесплатно.'],
                ['q' => 'Как быстро CityEE продаёт квартиру?', 'a' => 'Среднее время продажи — 30–45 дней. При правильной стратегии и активной рекламе результат часто быстрее — 2–3 недели.'],
            ],
        ],
        'en' => [
            'meta_title'       => 'Sell Property in Tallinn | Price Audit & Strategy | CityEE',
            'meta_description' => 'CityEE offers quality brokerage services for property sales — in a short time (1-1.5 months) and at the best price. Broker fee (commission) is minimal — just 2%.',
            'h1'               => 'Property Sales Brokerage',
            'hero_subtitle'    => 'Sell property at the best price in the shortest time!',
            'hero_add'         => '',
            'hero_cta'         => 'Send inquiry',
            'hero_bg'          => '/assets/templates/offshors/img/offshors.jpg',
            'intro'            => '<p><strong>REAL ESTATE BROKERAGE</strong> Selling property is an event that rarely happens in a person\'s life, so for the best and fastest result, it\'s worth entrusting this process to specialists. We help find solutions for both private and business clients.</p><p>You can request a personal price quote from our consultants in Tallinn or send us an inquiry.</p>',
            'services_title'   => 'OUR SERVICE INCLUDES:',
            'services' => [
                'Collecting and preparing necessary information about the property',
                'Determining the right selling price',
                'Professional photography',
                'Legal consultation and document verification',
                'Active sales management',
                'Regular feedback on sales activity',
                'Property presentation and all necessary materials when needed',
                'Notarial transaction monitoring',
                'Cooperation with other brokers — we share commission with everyone who brings us clients',
            ],
            'pricing_title'   => 'SERVICE PRICING',
            'pricing_text'    => '<p><i>The fee for organizing the sale is negotiable. It depends on the property selling price, location, and the scope of service you expect from the broker.</i></p><p><i>On average, the service cost is 2–5% of the transaction amount.</i></p>',
            'bonus'           => 'By signing an exclusive agreement with us, you get the maximum advertising package with a minimal commission — <strong>ONLY 2% of the apartment selling price!</strong>',
            'faq' => [
                ['q' => 'How long does it take to sell property?', 'a' => 'The average selling time is 1–1.5 months depending on the property and market price.'],
                ['q' => 'What is CityEE\'s commission?', 'a' => 'With an exclusive agreement, the commission is only 2% of the selling price. The standard commission is 2–5% of the transaction amount.'],
                ['q' => 'Is a free property valuation available?', 'a' => 'Yes, when signing an exclusive agreement (minimum 3 months), we offer a free property valuation.'],
            ],
            'answer_block' => [
                'question' => 'How to sell property in Tallinn at the best price?',
                'answer'   => 'CityEE conducts a market price audit, develops a pricing strategy, selects optimal advertising channels, and manages negotiations through to the notary. Average selling time is 30–45 days, commission from 2%.',
                'bullets'  => ['Market price audit and strategy', 'Professional photos and advertising', 'Buyer negotiations', 'Legal control through to notary'],
            ],
            'voice_qa' => [
                ['q' => 'How much does it cost to sell an apartment in Tallinn?', 'a' => 'CityEE broker commission is 2–5% of the transaction amount. With an exclusive agreement — just 2%. Valuation and first consultation are free.'],
                ['q' => 'How fast does CityEE sell apartments?', 'a' => 'Average selling time is 30–45 days. With the right strategy and active marketing, results are often faster — 2–3 weeks.'],
            ],
        ],
    ],

    // ─── RENT PAGE ─────────────────────────────────────────────
    'rent' => [
        'et' => [
            'meta_title'       => 'Kinnisvara üürileandmine Tallinnas | Usaldusväärne üürnik | CityEE',
            'meta_description' => 'Arvutame üüritootluse ja määrame õige hinna. Teeme professionaalseid fotosid ja käivitame aktiivse massireklaami. Vajadusel konsulteerime Teid huvitavates küsimustes, maksude ja muude kohustuste osas.',
            'h1'               => 'Kinnisvara üürileandmine',
            'hero_subtitle'    => 'Abi üürilepingu koostamisel',
            'hero_add'         => 'Potentsiaalse üürilevõtja kontrollimine',
            'hero_cta'         => 'Saada päring',
            'hero_bg'          => '/assets/templates/offshors/img/city.jpg',
            'intro'            => '<p>Enamike inimeste jaoks <strong>kinnisvara üürile andmine</strong> võib tunduda esialgu üsna lihtsa ülesandena, kuid ettenägematute probleemide ja tõrgete vältimiseks peab teadma seadusandlust, taustauuringu läbiviimise tööriistu ja olema inimeste heaks asjatundjaks. Meie spetsialistid aitavad leida Teile usaldusväärse üürniku. Me kontrollime potentsiaalset klienti hoolikalt ja aitame koostada Teile juriidiliselt korrektse lepingu.</p><p>Personaalset hinnapakkumist võib küsida meie konsultantidelt Tallinnas või saata meile päringu.</p>',
            'services_title'   => 'ÜÜRNIKU OTSIMISE TEENUS:',
            'services' => [
                'Arvutame üüritulu',
                'Õige üürihinna määramine',
                'Professionaalsed fotod',
                'Juriidiline konsultatsioon ja dokumentide õigsuse kontrollimine',
                'Otsime aktiivselt üürnikku',
                'Konsulteerime maksude ja muude kohustuste osas',
                'Vajadusel korraldame kinnisvara presentatsiooni ja kõik selleks vajalikud materjalid.',
                'Teostame kliendi andmete kontrolli',
                'Teeme koostööd teiste kinnisvara büroodega ja jagame vahendustasu kõigiga, kes toovad meile kliente',
            ],
            'pricing_title'   => 'TEENUSE PAKKUMISE HIND',
            'pricing_text'    => '<p><i>Üürniku otsimine ja õigesti koostatud üürilepingu allkirjastamine on tavaliselt ühe kuu üüritasu.</i></p>',
            'bonus'           => '',
            'faq' => [
                ['q' => 'Mis maksab üürniku otsimise teenus?', 'a' => 'Tavaliselt ühe kuu üüritasu, sisaldab üürniku taustauuringut ja lepingu koostamist.'],
                ['q' => 'Kuidas kontrollitakse üürnikku?', 'a' => 'Teostame kliendi andmete ja tausta kontroll, et tagada usaldusväärne üürnik.'],
            ],
            'answer_block' => [
                'question' => 'Kuidas anda kinnisvara üürile Tallinnas turvaliselt?',
                'answer'   => 'CityEE aitab arvutada üüritootluse, määrata õige üürihinna, leida usaldusväärne üürnik ja koostada juriidiliselt korrektne leping. Teenus sisaldab üürniku taustauuringut ja täielikku dokumentatsiooni.',
                'bullets'  => ['Üüritootluse arvutamine', 'Õige üürihinna määramine', 'Üürniku taustauuringud', 'Juriidiliselt korrektne leping'],
            ],
            'voice_qa' => [
                ['q' => 'Kui palju maksab kinnisvara üürile andmine Tallinnas?', 'a' => 'CityEE üürniku otsimise teenus on tavaliselt ühe kuu üüritasu. See sisaldab taustauuringut, professionaalseid fotosid ja lepingu koostamist.'],
            ],
        ],
        'ru' => [
            'meta_title'       => 'Сдать недвижимость в Таллинне | Надёжный арендатор | CityEE',
            'meta_description' => 'Рассчитаем доходность аренды и определим правильную цену. Сделаем профессиональные фотографии и запустим активную массовую рекламу. Проконсультируем по вопросам налогов и обязательств.',
            'h1'               => 'Сдача недвижимости в аренду',
            'hero_subtitle'    => 'Помощь в составлении договора аренды',
            'hero_add'         => 'Проверка потенциального арендатора',
            'hero_cta'         => 'Отправить заявку',
            'hero_bg'          => '/assets/templates/offshors/img/city.jpg',
            'intro'            => '<p>Для большинства людей <strong>сдача недвижимости в аренду</strong> может показаться поначалу довольно простой задачей, однако для избежания непредвиденных проблем нужно знать законодательство, инструменты проверки и быть экспертом в работе с людьми. Наши специалисты помогут найти надежного арендатора. Мы тщательно проверяем потенциального клиента и помогаем составить юридически корректный договор.</p><p>За персональным ценовым предложением можно обратиться к нашим консультантам в Таллинне или отправить нам запрос.</p>',
            'services_title'   => 'УСЛУГА ПОИСКА АРЕНДАТОРА:',
            'services' => [
                'Рассчитаем арендный доход',
                'Определение правильной арендной цены',
                'Профессиональные фотографии',
                'Юридическая консультация и проверка правильности документов',
                'Активно ищем арендатора',
                'Консультируем по вопросам налогов и других обязательств',
                'При необходимости организуем презентацию недвижимости и все необходимые материалы',
                'Проводим проверку данных клиента',
                'Сотрудничаем с другими бюро недвижимости и делим комиссию со всеми, кто приводит клиентов',
            ],
            'pricing_title'   => 'СТОИМОСТЬ УСЛУГИ',
            'pricing_text'    => '<p><i>Поиск арендатора и подписание правильно составленного договора аренды — обычно стоимость одного месяца аренды.</i></p>',
            'bonus'           => '',
            'faq' => [
                ['q' => 'Сколько стоит услуга поиска арендатора?', 'a' => 'Обычно стоимость одного месяца аренды, включая проверку арендатора и составление договора.'],
                ['q' => 'Как проверяется арендатор?', 'a' => 'Мы проводим проверку данных и репутации клиента для обеспечения надёжности арендатора.'],
            ],
            'answer_block' => [
                'question' => 'Как безопасно сдать недвижимость в аренду в Таллинне?',
                'answer'   => 'CityEE рассчитывает арендную доходность, определяет правильную цену аренды, находит надёжного арендатора и составляет юридически корректный договор. Услуга включает проверку арендатора и полную документацию.',
                'bullets'  => ['Расчёт арендной доходности', 'Определение правильной цены', 'Проверка арендатора', 'Юридически корректный договор'],
            ],
            'voice_qa' => [
                ['q' => 'Сколько стоит сдать квартиру в аренду в Таллинне?', 'a' => 'Услуга CityEE по поиску арендатора стоит обычно одну месячную аренду. Включает проверку арендатора, профессиональные фото и составление договора.'],
            ],
        ],
        'en' => [
            'meta_title'       => 'Rent Out Property in Tallinn | Reliable Tenant | CityEE',
            'meta_description' => 'We calculate rental yield, set the right price, take professional photos, and launch active advertising. We also consult on taxes and obligations.',
            'h1'               => 'Property Rental Services',
            'hero_subtitle'    => 'Help with lease agreement preparation',
            'hero_add'         => 'Potential tenant verification',
            'hero_cta'         => 'Send inquiry',
            'hero_bg'          => '/assets/templates/offshors/img/city.jpg',
            'intro'            => '<p>For most people, <strong>renting out property</strong> may initially seem like a simple task, but to avoid unforeseen problems, you need to know legislation, background check tools, and be an expert in working with people. Our specialists will help you find a reliable tenant. We carefully check potential clients and help prepare a legally correct lease agreement.</p><p>You can request a personal price quote from our consultants in Tallinn or send us an inquiry.</p>',
            'services_title'   => 'TENANT SEARCH SERVICE:',
            'services' => [
                'We calculate rental income',
                'Determining the right rental price',
                'Professional photography',
                'Legal consultation and document verification',
                'Active tenant search',
                'Consulting on taxes and other obligations',
                'Property presentation and all necessary materials when needed',
                'Client background verification',
                'Cooperation with other real estate offices — sharing commission with all who bring clients',
            ],
            'pricing_title'   => 'SERVICE PRICING',
            'pricing_text'    => '<p><i>Tenant search and signing a properly prepared lease agreement is typically one month\'s rent.</i></p>',
            'bonus'           => '',
            'faq' => [
                ['q' => 'How much does the tenant search service cost?', 'a' => 'Typically one month\'s rent, including tenant background check and lease agreement preparation.'],
                ['q' => 'How is the tenant verified?', 'a' => 'We conduct thorough background and data checks to ensure a reliable tenant.'],
            ],
            'answer_block' => [
                'question' => 'How to safely rent out property in Tallinn?',
                'answer'   => 'CityEE calculates rental yield, determines the right rental price, finds a reliable tenant, and prepares a legally correct lease agreement. The service includes tenant background checks and full documentation.',
                'bullets'  => ['Rental yield calculation', 'Correct rental pricing', 'Tenant background checks', 'Legally correct lease agreement'],
            ],
            'voice_qa' => [
                ['q' => 'How much does it cost to rent out an apartment in Tallinn?', 'a' => 'CityEE tenant search service typically costs one month\'s rent. Includes background checks, professional photos, and lease preparation.'],
            ],
        ],
    ],

    // ─── CONSULTATION PAGE ─────────────────────────────────────
    'consultation' => [
        'et' => [
            'meta_title'       => 'Kinnisvara konsultatsioon Tallinnas | Hindamine ja juriidiline abi | CityEE',
            'meta_description' => 'CityEE kinnisvaravahendaja pakub konsultatsioone finants- ja varaõiguse küsimustes. Leiame Sulle parima kodu Tallinnas. Kinnisvara esmane kontroll ja dokumentatsiooni kontroll.',
            'h1'               => 'Konsulteerimine',
            'hero_subtitle'    => 'Konsulteerime kinnisvara ostu ja müügi korral.',
            'hero_subtitle2'   => 'Objekti õige turuhinna määramine.',
            'hero_add'         => 'Pakume konsultatsioone finants- ja varaõiguse küsimustes.',
            'hero_cta'         => 'Telli konsultatsioon',
            'hero_bg'          => '/assets/templates/offshors/img/banks-bg.jpg',
            'intro'            => '<p>Iga kinnisvaraga seotud tehing või protsess on ainulaadne, mis esmapilgul tundub lihtne, võib varjata nii riske kui ka võimalusi.</p><p>Hindame olukorda kompleksselt ja aitame leida kliendile sobiva lahenduse. Me pakume parimaid võimalusi ja maandame kõiki riske.</p>',
            'services_title'   => '',
            'services' => [
                'Kinnisvara vahendamine',
                'Objektide valik tellimuse alusel soovijale osta objekt Tallinnas või väljaspool linna.',
                'Esmane ülevaatus ja kinnisvara legaliseerimise dokumentatsiooni kontroll',
                'Kinnisvara hindamine Tallinn ja Harjumaa',
                'Ehitusloa saamise protsessi juhtimine',
                'Kinnisvara kasutusloa saamise protsessi juhtimine.',
                'Juriidiline konsultatsioon kinnisvara alal.',
                'Kinnisvara dokumentatsiooni ettevalmistamine ja koostamine',
                'Abi kinnisvara ostmiseks laenu saamisel',
            ],
            'bonus'           => 'Esmane kinnisvaraalane juriidiline konsultatsioon ja nõustamine telefoni teel või online on <strong>- TASUTA!</strong>',
            'pricing_title'   => 'Teenuste eest tasumise',
            'pricing_table' => [
                ['service' => 'Kinnisvaravahendus', 'price' => '2-3%'],
                ['service' => 'Objektide valik tellimuse alusel', 'price' => '200 EUR'],
                ['service' => 'Kinnisvara hindamine', 'price' => '300 EUR'],
                ['service' => 'Dokumentatsiooni esmane ülevaatus ja kontroll', 'price' => '150 EUR'],
                ['service' => 'Ehitusloa saamine', 'price' => '1500 EUR'],
                ['service' => 'Kasutusloa saamine', 'price' => '1500 EUR'],
            ],
            'faq' => [
                ['q' => 'Kas esmane konsultatsioon on tasuta?', 'a' => 'Jah, esmane kinnisvaraalane juriidiline konsultatsioon telefoni teel või online on tasuta.'],
                ['q' => 'Millistes küsimustes te konsulteerite?', 'a' => 'Konsulteerime finants- ja varaõiguse küsimustes, aitame kinnisvara ostu-müügi tehingutes, hindamisel ja dokumentatsioonis.'],
            ],
        ],
        'ru' => [
            'meta_title'       => 'Консультация по недвижимости Таллинн | Оценка и юридическая помощь | CityEE',
            'meta_description' => 'Посредник CityEE предлагает консультации по финансовым и имущественным вопросам. Найдём лучшее жильё в Таллинне. Первичная проверка и проверка документации.',
            'h1'               => 'Консультирование',
            'hero_subtitle'    => 'Консультируем при покупке и продаже недвижимости.',
            'hero_subtitle2'   => 'Определение правильной рыночной цены объекта.',
            'hero_add'         => 'Предлагаем консультации по финансовым и имущественным вопросам.',
            'hero_cta'         => 'Заказать консультацию',
            'hero_bg'          => '/assets/templates/offshors/img/banks-bg.jpg',
            'intro'            => '<p>Каждая сделка или процесс, связанный с недвижимостью, уникальны — то, что кажется простым на первый взгляд, может скрывать как риски, так и возможности.</p><p>Мы оцениваем ситуацию комплексно и помогаем найти подходящее решение для клиента. Мы предлагаем лучшие возможности и минимизируем все риски.</p>',
            'services_title'   => '',
            'services' => [
                'Посредничество в сфере недвижимости',
                'Подбор объектов по заказу для покупки в Таллинне или за городом.',
                'Первичный осмотр и проверка документации по легализации недвижимости',
                'Оценка недвижимости в Таллинне и Харьюмаа',
                'Управление процессом получения разрешения на строительство',
                'Управление процессом получения эксплуатационного разрешения.',
                'Юридическая консультация в сфере недвижимости.',
                'Подготовка и составление документации на недвижимость',
                'Помощь в получении кредита для покупки недвижимости',
            ],
            'bonus'           => 'Первичная юридическая консультация по недвижимости по телефону или онлайн — <strong>БЕСПЛАТНО!</strong>',
            'pricing_title'   => 'Стоимость услуг',
            'pricing_table' => [
                ['service' => 'Посредничество', 'price' => '2-3%'],
                ['service' => 'Подбор объектов по заказу', 'price' => '200 EUR'],
                ['service' => 'Оценка недвижимости', 'price' => '300 EUR'],
                ['service' => 'Первичный осмотр документации', 'price' => '150 EUR'],
                ['service' => 'Получение разрешения на строительство', 'price' => '1500 EUR'],
                ['service' => 'Получение эксплуатационного разрешения', 'price' => '1500 EUR'],
            ],
            'faq' => [
                ['q' => 'Первичная консультация бесплатна?', 'a' => 'Да, первичная юридическая консультация по недвижимости по телефону или онлайн — бесплатно.'],
                ['q' => 'По каким вопросам вы консультируете?', 'a' => 'Консультируем по финансовым и имущественным вопросам, помогаем при сделках купли-продажи, оценке и документации.'],
            ],
        ],
        'en' => [
            'meta_title'       => 'Real Estate Consultation Tallinn | Valuation & Legal Help | CityEE',
            'meta_description' => 'CityEE offers consultations on financial and property matters. We find the best home in Tallinn for you. Initial inspection and documentation check.',
            'h1'               => 'Consultation',
            'hero_subtitle'    => 'We consult on buying and selling real estate.',
            'hero_subtitle2'   => 'Determining the correct market price of the property.',
            'hero_add'         => 'We offer consultations on financial and property law matters.',
            'hero_cta'         => 'Book a consultation',
            'hero_bg'          => '/assets/templates/offshors/img/banks-bg.jpg',
            'intro'            => '<p>Every real estate transaction or process is unique — what may seem simple at first glance can hide both risks and opportunities.</p><p>We assess the situation comprehensively and help find the right solution for the client. We offer the best options and mitigate all risks.</p>',
            'services_title'   => '',
            'services' => [
                'Real estate brokerage',
                'Property selection on request for buyers in Tallinn or outside the city.',
                'Initial inspection and property legalization documentation check',
                'Property valuation in Tallinn and Harjumaa',
                'Building permit process management',
                'Usage permit process management.',
                'Legal consultation in real estate.',
                'Preparation and compilation of property documentation',
                'Assistance in obtaining a loan for property purchase',
            ],
            'bonus'           => 'Initial legal real estate consultation by phone or online is <strong>FREE!</strong>',
            'pricing_title'   => 'Service Pricing',
            'pricing_table' => [
                ['service' => 'Brokerage', 'price' => '2-3%'],
                ['service' => 'Property selection on request', 'price' => '200 EUR'],
                ['service' => 'Property valuation', 'price' => '300 EUR'],
                ['service' => 'Initial documentation review', 'price' => '150 EUR'],
                ['service' => 'Building permit', 'price' => '1500 EUR'],
                ['service' => 'Usage permit', 'price' => '1500 EUR'],
            ],
            'faq' => [
                ['q' => 'Is the initial consultation free?', 'a' => 'Yes, the initial legal real estate consultation by phone or online is free of charge.'],
                ['q' => 'What questions do you consult on?', 'a' => 'We consult on financial and property matters, help with purchase-sale transactions, valuation, and documentation.'],
            ],
        ],
    ],

    // ─── CONTACTS PAGE ─────────────────────────────────────────
    'contacts' => [
        'et' => [
            'meta_title'       => 'Kontaktid | CityEE Kinnisvara Tallinn | Viru väljak 2',
            'meta_description' => 'Meil on partnerid Venemaal, Rootsis, Soomes ja Eestis. Keskmiselt 1 kuu on korteri müügiaeg. Meie on üle 120000 kontakti reklaami võrgustikus.',
            'h1'               => 'Kontaktid',
            'office_label'     => 'Kinnisvarabüroo:',
            'address_label'    => 'Aadres:',
            'phone_label'      => 'Telefoni number:',
            'app_phones'       => 'Rakenduste telefonid:',
            'email_label'      => 'Email:',
            'map_label'        => 'Kaardil:',
        ],
        'ru' => [
            'meta_title'       => 'Контакты | CityEE Недвижимость Tallinn | Viru väljak 2',
            'meta_description' => 'У нас есть партнёры в России, Швеции, Финляндии и Эстонии. Средний срок продажи квартиры — 1 месяц. Более 120000 контактов в рекламной сети.',
            'h1'               => 'Контакты',
            'office_label'     => 'Агентство недвижимости:',
            'address_label'    => 'Адрес:',
            'phone_label'      => 'Номер телефона:',
            'app_phones'       => 'Телефоны в приложениях:',
            'email_label'      => 'Email:',
            'map_label'        => 'На карте:',
        ],
        'en' => [
            'meta_title'       => 'Contacts | CityEE Real Estate Tallinn | Viru väljak 2',
            'meta_description' => 'We have partners in Russia, Sweden, Finland, and Estonia. Average apartment selling time is 1 month. Over 120,000 contacts in our advertising network.',
            'h1'               => 'Contacts',
            'office_label'     => 'Real Estate Office:',
            'address_label'    => 'Address:',
            'phone_label'      => 'Phone number:',
            'app_phones'       => 'App phones:',
            'email_label'      => 'Email:',
            'map_label'        => 'On the map:',
        ],
    ],

    // ─── HOME PAGE ─────────────────────────────────────────────
    'home' => [
        'et' => [
            'meta_title'       => 'Kinnisvara müük ja üür Tallinn & Harjumaa | CityEE',
            'meta_description' => 'CityEE — kinnisvaratehingute optimeerimise partner Tallinnas ja Harjumaal. Müügistrateegia, turuaudit, läbirääkimised. 10+ aastat, 300+ tehingut, 2% komisjon.',
            'h1'               => 'KAS SOOVITE OSTA VÕI MÜÜA',
            'h1_span'          => 'ANDA OMA KINNISVARA ÜÜRILE?',
            'banner_text'      => '<span>Meie spetsialistid aitavad Teid sellega.</span> Professionaalne online konsultatsioon!',
            'banner2_h2'       => 'VALIME OPTIMAALSE VARIANDI',
            'banner2_span'     => 'ASUKOHA JA INFRASTRUKTUURI PÕHJAL',
            'banner2_text'     => '<span>Kliendi huvide kaitsmine. Kontrollime arendajat, hindame riske!</span>',
            'banner3_h2'       => 'SÄÄSTKE KORTERI MÜÜGIAEGA 2 KORDA',
            'banner3_span'     => 'TEIE ISIKLIK MÜÜGIEKSPERT AITAB TEID',
            'banner3_text'     => '<span>Objekti professionaalne reklaam</span>Kompleksne lähenemisviis teenuste pakkumisele',
            'advantages_title' => 'MEIEGA KOOSTÖÖ EELISED',
            'offers_title'     => 'MEIE PAKKUME',
            'offers_apartments' => 'Korterid',
            'offers_houses'    => 'Majad ja maatükkid',
            'offers_commercial' => 'Ärihooned',
            'offers_bonus'     => 'Sõlmides meiega ainusesinduslepingu, saate oma kinnisvara müügiks maksimaalse reklaamipaketi minimaalse vahendustasuga <strong>AINULT 2% korteri müügihinnast !</strong>',
            'services_title'   => 'Meie teenused',
            'srv_sell'         => 'Kinnisvara müük',
            'srv_sell_desc'    => 'Parima müügikanali valimine<br/>Tasuta hinnakonsultatsioon',
            'srv_rent'         => 'Kinnisvara üürile andmine',
            'srv_rent_desc'    => 'Usaldusväärse üürniku otsimine<br/>Aitame koostada korrektse lepingu<br/>Konsulteerime maksu ja muude kohustuste osas',
            'srv_consult'      => 'Konsultatsioon',
            'srv_consult_desc' => 'Ostu-müügitehingute ettevalmistamine<br/>Maksimaalne konfidentsiaalsus',
            'deals_title'      => 'TEHTUD TEHINGUD',
            'result_title'     => 'SOOVID TULEMUST?',
            'result_subtitle'  => 'Väga professionaalne ja kiire teenindus!',
            'result_agent_title' => 'Teie isiklik maakler',
            'result_cta'       => 'Võta ühendust',
            'steps_title'      => 'MEIGA KOOSTÖÖ ETAPID',
            'steps'            => ['KONSULTATSIOON', 'DOKUMENTIDE<br/> ETTEVALMISTAMINE', 'AKTIIVNE MÜÜK', 'NOTARITEHING'],
            'team_title'       => 'MEIE TÖÖTAJAD',
        ],
        'ru' => [
            'meta_title'       => 'Продажа и аренда недвижимости Tallinn & Harjumaa | CityEE',
            'meta_description' => 'CityEE — партнёр по оптимизации сделок с недвижимостью в Tallinn и Harjumaa. Стратегия продажи, аудит цены, переговоры. 10+ лет, 300+ сделок, комиссия 2%.',
            'h1'               => 'ХОТИТЕ КУПИТЬ ИЛИ ПРОДАТЬ',
            'h1_span'          => 'СДАТЬ ВАШУ НЕДВИЖИМОСТЬ В АРЕНДУ?',
            'banner_text'      => '<span>Наши специалисты помогут вам в этом.</span> Профессиональная онлайн-консультация!',
            'banner2_h2'       => 'ВЫБИРАЕМ ОПТИМАЛЬНЫЙ ВАРИАНТ',
            'banner2_span'     => 'ПО РАСПОЛОЖЕНИЮ И ИНФРАСТРУКТУРЕ',
            'banner2_text'     => '<span>Защита интересов клиента. Проверяем застройщика, оцениваем риски!</span>',
            'banner3_h2'       => 'СЭКОНОМЬТЕ ВРЕМЯ ПРОДАЖИ КВАРТИРЫ В 2 РАЗА',
            'banner3_span'     => 'ВАШ ЛИЧНЫЙ ЭКСПЕРТ ПО ПРОДАЖАМ ПОМОЖЕТ ВАМ',
            'banner3_text'     => '<span>Профессиональная реклама объекта</span>Комплексный подход к предоставлению услуг',
            'advantages_title' => 'ПРЕИМУЩЕСТВА РАБОТЫ С НАМИ',
            'offers_title'     => 'МЫ ПРЕДЛАГАЕМ',
            'offers_apartments' => 'Квартиры',
            'offers_houses'    => 'Дома и участки',
            'offers_commercial' => 'Коммерческие здания',
            'offers_bonus'     => 'Заключив с нами эксклюзивный договор, вы получите максимальный рекламный пакет для продажи недвижимости с минимальной комиссией — <strong>ВСЕГО 2% от цены продажи квартиры!</strong>',
            'services_title'   => 'Наши услуги',
            'srv_sell'         => 'Продажа недвижимости',
            'srv_sell_desc'    => 'Выбор лучшего канала продаж<br/>Бесплатная ценовая консультация',
            'srv_rent'         => 'Сдача недвижимости в аренду',
            'srv_rent_desc'    => 'Поиск надёжного арендатора<br/>Помогаем составить корректный договор<br/>Консультируем по налогам и другим обязательствам',
            'srv_consult'      => 'Консультация',
            'srv_consult_desc' => 'Подготовка сделок купли-продажи<br/>Максимальная конфиденциальность',
            'deals_title'      => 'ЗАВЕРШЕННЫЕ СДЕЛКИ',
            'result_title'     => 'ХОТИТЕ РЕЗУЛЬТАТ?',
            'result_subtitle'  => 'Профессиональное и быстрое обслуживание!',
            'result_agent_title' => 'Ваш личный маклер',
            'result_cta'       => 'Связаться',
            'steps_title'      => 'ЭТАПЫ НАШЕГО СОТРУДНИЧЕСТВА',
            'steps'            => ['КОНСУЛЬТАЦИЯ', 'ПОДГОТОВКА<br/> ДОКУМЕНТОВ', 'АКТИВНАЯ ПРОДАЖА', 'НОТАРИАЛЬНАЯ СДЕЛКА'],
            'team_title'       => 'НАШИ СОТРУДНИКИ',
        ],
        'en' => [
            'meta_title'       => 'Real Estate Sale & Rental Tallinn & Harjumaa | CityEE',
            'meta_description' => 'CityEE — real estate deal optimization partner in Tallinn & Harjumaa. Sale strategy, price audit, negotiation. 10+ years, 300+ deals, 2% commission.',
            'h1'               => 'LOOKING TO BUY OR SELL',
            'h1_span'          => 'RENT OUT YOUR PROPERTY?',
            'banner_text'      => '<span>Our specialists will help you with that.</span> Professional online consultation!',
            'banner2_h2'       => 'WE CHOOSE THE OPTIMAL OPTION',
            'banner2_span'     => 'BASED ON LOCATION AND INFRASTRUCTURE',
            'banner2_text'     => '<span>Protecting client interests. We check the developer, assess risks!</span>',
            'banner3_h2'       => 'SAVE HALF THE TIME ON APARTMENT SALES',
            'banner3_span'     => 'YOUR PERSONAL SALES EXPERT WILL HELP YOU',
            'banner3_text'     => '<span>Professional property advertising</span>Comprehensive approach to service delivery',
            'advantages_title' => 'ADVANTAGES OF WORKING WITH US',
            'offers_title'     => 'WE OFFER',
            'offers_apartments' => 'Apartments',
            'offers_houses'    => 'Houses and plots',
            'offers_commercial' => 'Commercial buildings',
            'offers_bonus'     => 'By signing an exclusive agreement with us, you get the maximum advertising package with minimal commission — <strong>ONLY 2% of the apartment selling price!</strong>',
            'services_title'   => 'Our Services',
            'srv_sell'         => 'Property Sales',
            'srv_sell_desc'    => 'Choosing the best sales channel<br/>Free price consultation',
            'srv_rent'         => 'Property Rental',
            'srv_rent_desc'    => 'Finding a reliable tenant<br/>Helping draft a proper lease<br/>Tax and obligation consulting',
            'srv_consult'      => 'Consultation',
            'srv_consult_desc' => 'Purchase-sale transaction preparation<br/>Maximum confidentiality',
            'deals_title'      => 'COMPLETED DEALS',
            'result_title'     => 'WANT RESULTS?',
            'result_subtitle'  => 'Professional and fast service!',
            'result_agent_title' => 'Your personal broker',
            'result_cta'       => 'Contact us',
            'steps_title'      => 'OUR COOPERATION STAGES',
            'steps'            => ['CONSULTATION', 'DOCUMENT<br/> PREPARATION', 'ACTIVE SALES', 'NOTARIAL DEAL'],
            'team_title'       => 'OUR TEAM',
        ],
    ],

    // ─── WHY CITYEE PAGE ──────────────────────────────────────
    'why' => [
        'et' => [
            'meta_title'       => 'Miks valida CityEE? | Võrdlus: ise vs maakler | CityEE Tallinn',
            'meta_description' => 'Miks valida CityEE kinnisvaramaakler? Struktureeritud turuaudit, läbirääkimisstrateegia, 2% vahendustasu, keskmiselt 1-1,5 kuu müügiaeg Tallinn & Harjumaa.',
            'h1'               => 'Miks CityEE?',
            'hero_subtitle'    => 'Kinnisvaratehingute optimeerimise partner Tallinnas ja Harjumaal',
            'hero_bg'          => '/assets/templates/offshors/img/offshors.jpg',
        ],
        'ru' => [
            'meta_title'       => 'Почему CityEE? | Сравнение: сам vs маклер | CityEE Tallinn',
            'meta_description' => 'Почему выбирают маклера CityEE? Структурированный аудит рынка, переговорная стратегия, комиссия 2%, средний срок продажи 1-1,5 месяца. Tallinn & Harjumaa.',
            'h1'               => 'Почему CityEE?',
            'hero_subtitle'    => 'Партнер по оптимизации сделок с недвижимостью в Таллинне и Харьюмаа',
            'hero_bg'          => '/assets/templates/offshors/img/offshors.jpg',
        ],
        'en' => [
            'meta_title'       => 'Why CityEE? | Private vs Agent vs CityEE | CityEE Tallinn',
            'meta_description' => 'Why choose CityEE? Structured market audit, negotiation strategy, 2% commission, average selling time 1 month.',
            'h1'               => 'Why CityEE?',
            'hero_subtitle'    => 'Real estate deal optimization partner in Tallinn and Harjumaa',
            'hero_bg'          => '/assets/templates/offshors/img/offshors.jpg',
        ],
    ],

    // ─── AUDIT PAGE ───────────────────────────────────────────
    'audit' => [
        'et' => [
            'meta_title'       => 'Kinnisvara audit - Struktureeritud turuanalüüs | CityEE Tallinn',
            'meta_description' => 'Tellige professionaalne kinnisvara audit. Reaalne hinnakorridor, konkurentide analüüs, müügistrateegia 30-45 päevaks. Tasuta esmane analüüs.',
            'h1'               => 'Kinnisvara audit',
            'hero_subtitle'    => 'Struktureeritud turuanalüüs ja müügistrateegia',
            'hero_bg'          => '/assets/templates/offshors/img/offshors.jpg',
            'problem_title'    => '80% omanikest kaotavad raha mitte objekti tõttu, vaid vale strateegia tõttu.',
            'audit_title'      => 'Mida audit sisaldab',
            'audit_items'      => [
                'Reaalne hinnakorridor',
                'Aktiivsed analoogid turul',
                'Broneeritud analoogid',
                'Müüdud analoogidtegelike tehinguhindadega',
                'Kuulutuse esitluse nõrkused',
                'Fotostrateegia',
                'Läbirääkimisstrateegia',
                'Plaan 30-45 päevaks',
            ],
            'for_whom_title'   => 'Kellele on audit kasulik',
            'for_whom'         => [
                'Neile, kes alles plaanivad müüa',
                'Neile, kes on juba kuulutuse avaldanud',
                'Neile, kes "ripuvad" 1-3 kuud ilma tulemuseta',
            ],
            'form_title'       => 'Tellige audit',
            'form_type'        => 'Objekti tüüp',
            'form_apartment'   => 'Korter',
            'form_house'       => 'Maja',
            'form_commercial'  => 'Äriruum',
            'form_district'    => 'Piirkond',
            'form_area'        => 'Pindala (m²)',
            'form_link'        => 'Link kuulutusele (kui on)',
            'form_phone'       => 'Telefon / WhatsApp',
            'form_submit'      => 'Telli audit',
            'form_note'        => 'Ilma ettemaksuta. Esmane analüüs on tasuta.',
            'faq' => [
                ['q' => 'Kui palju kinnisvara audit maksab?', 'a' => 'Esmane analüüs on tasuta. Täisaudit koos müügistrateegiaga sisaldub ainuesinduslepingus.'],
                ['q' => 'Kui kaua audit aega võtab?', 'a' => '24 tunni jooksul saate esimese tagasiside koos hinnakorrido ja turupositsiooniga.'],
                ['q' => 'Kas audit kohustab tehingule?', 'a' => 'Ei. Audit on informatsioon. Otsuse teete Teie.'],
            ],
        ],
        'ru' => [
            'meta_title'       => 'Аудит недвижимости - Структурированный анализ рынка | CityEE Tallinn',
            'meta_description' => 'Закажите профессиональный аудит недвижимости. Реальный ценовой коридор, анализ конкурентов, стратегия продажи на 30-45 дней. Бесплатный первичный анализ.',
            'h1'               => 'Аудит недвижимости',
            'hero_subtitle'    => 'Структурированный анализ рынка и стратегия продажи',
            'hero_bg'          => '/assets/templates/offshors/img/offshors.jpg',
            'problem_title'    => '80% собственников теряют деньги не из-за объекта, а из-за неправильной стратегии.',
            'audit_title'      => 'Что включает аудит',
            'audit_items'      => [
                'Реальный ценовой коридор',
                'Активные аналоги на рынке',
                'Аналоги в бронировании',
                'Проданные аналоги с реальными ценами сделок',
                'Слабые места подачи объявления',
                'Фото-стратегия',
                'Переговорная стратегия',
                'План на 30-45 дней',
            ],
            'for_whom_title'   => 'Для кого полезен аудит',
            'for_whom'         => [
                'Тем, кто только планирует продавать',
                'Тем, кто уже разместил объявление',
                'Тем, кто "висит" 1-3 месяца без результата',
            ],
            'form_title'       => 'Заказать аудит',
            'form_type'        => 'Тип объекта',
            'form_apartment'   => 'Квартира',
            'form_house'       => 'Дом',
            'form_commercial'  => 'Коммерческое',
            'form_district'    => 'Район',
            'form_area'        => 'Площадь (м²)',
            'form_link'        => 'Ссылка на объявление (если есть)',
            'form_phone'       => 'Телефон / WhatsApp',
            'form_submit'      => 'Заказать аудит',
            'form_note'        => 'Без аванса. Первичный анализ бесплатно.',
            'faq' => [
                ['q' => 'Сколько стоит аудит недвижимости?', 'a' => 'Первичный анализ бесплатно. Полный аудит с стратегией продажи входит в эксклюзивный договор.'],
                ['q' => 'Сколько времени занимает аудит?', 'a' => 'В течение 24 часов вы получите первую обратную связь с ценовым коридором и позицией на рынке.'],
                ['q' => 'Аудит обязывает к сделке?', 'a' => 'Нет. Аудит — это информация. Решение принимаете вы.'],
            ],
        ],
        'en' => [
            'meta_title'       => 'Property Audit - Structured Market Analysis | CityEE Tallinn',
            'meta_description' => 'Order a professional property audit. Real price corridor, competitor analysis, sales strategy for 30-45 days. Free initial analysis.',
            'h1'               => 'Property Audit',
            'hero_subtitle'    => 'Structured market analysis and sales strategy',
            'hero_bg'          => '/assets/templates/offshors/img/offshors.jpg',
            'problem_title'    => '80% of owners lose money not because of the property, but because of the wrong strategy.',
            'audit_title'      => 'What the audit includes',
            'audit_items'      => [
                'Real price corridor',
                'Active comparable listings',
                'Reserved comparables',
                'Sold comparables with actual transaction prices',
                'Listing presentation weaknesses',
                'Photo strategy',
                'Negotiation strategy',
                'Plan for 30-45 days',
            ],
            'for_whom_title'   => 'Who benefits from an audit',
            'for_whom'         => [
                'Those who are just planning to sell',
                'Those who have already listed',
                'Those who have been listed for 1-3 months without results',
            ],
            'form_title'       => 'Order Audit',
            'form_type'        => 'Property type',
            'form_apartment'   => 'Apartment',
            'form_house'       => 'House',
            'form_commercial'  => 'Commercial',
            'form_district'    => 'District',
            'form_area'        => 'Area (m²)',
            'form_link'        => 'Link to listing (if available)',
            'form_phone'       => 'Phone / WhatsApp',
            'form_submit'      => 'Order Audit',
            'form_note'        => 'No advance payment. Initial analysis is free.',
            'faq' => [
                ['q' => 'How much does a property audit cost?', 'a' => 'Initial analysis is free. Full audit with sales strategy is included in the exclusive agreement.'],
                ['q' => 'How long does the audit take?', 'a' => 'Within 24 hours you will receive initial feedback with price corridor and market positioning.'],
                ['q' => 'Does the audit obligate to a deal?', 'a' => 'No. The audit is information. The decision is yours.'],
            ],
        ],
    ],

    // ─── Metrika IDs ───────────────────────────────────────────
    'metrika' => [
        'et' => '87598929',
        'ru' => '87599735',
        'en' => '87598929',
    ],
];
